# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qr_rcpp_omega <- function(Y, W, omega, lambda, tau, qn, zeta, zetaincre, maxit, tol) {
    .Call('_qrpQuanReg_qr_rcpp_omega', PACKAGE = 'qrpQuanReg', Y, W, omega, lambda, tau, qn, zeta, zetaincre, maxit, tol)
}

qr_rcpp <- function(Y, W, lambda, tau, L, qn, zeta, zetaincre, maxit, tol) {
    .Call('_qrpQuanReg_qr_rcpp', PACKAGE = 'qrpQuanReg', Y, W, lambda, tau, L, qn, zeta, zetaincre, maxit, tol)
}

